version: '3.8'

services:
  enpal:
    image: michaelantonfischer/enpal-modbus
    ports:
      - "502:502"
    environment:
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_ORG_ID=${INFLUX_ORG_ID}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_TOKEN=${INFLUX_TOKEN}